// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var Finished = Caml_exceptions.create("Exception-ReasonMl.Finished");

var Exception = Caml_exceptions.create("Exception-ReasonMl.Exception");

throw [
      Exception,
      "something went wrong"
    ];

exports.Finished = Finished;
exports.Exception = Exception;
/*  Not a pure module */
