// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function add(a, b) {
  return a + b | 0;
}

function getHello(param) {
  return "Hello";
}

var result = "Hello";

console.log(result);

exports.add = add;
exports.getHello = getHello;
exports.result = result;
/*  Not a pure module */
