// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

for(var i = 0; i <= 10; ++i){
  Pervasives.print_int(i);
}

for(var i$1 = 8; i$1 >= 0; --i$1){
  Pervasives.print_int(i$1);
}

var i$2 = {
  contents: 0
};

while(Caml_obj.caml_lessthan(i$2, {
        contents: 8
      })) {
  i$2.contents = i$2.contents + 1 | 0;
  console.log(i$2);
};

exports.i = i$2;
/*  Not a pure module */
