// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");

var array = [
  "adil",
  "shaikh",
  "hello"
];

console.log(Caml_array.caml_array_get(array, 0));

Caml_array.caml_array_set(array, 0, "Baba");

console.log(Caml_array.caml_array_get(array, 0));

var luke = {
  firstname: "Luke",
  lastname: "Harper"
};

luke.lastname = "shaikh";

console.log(luke);

exports.array = array;
exports.luke = luke;
/*  Not a pure module */
