// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var x = {
  contents: 5
};

console.log(x);

x.contents = x.contents + 5 | 0;

console.log(x.contents);

exports.x = x;
/*  Not a pure module */
