// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function swap(x, y) {
  return /* tuple */[
          y,
          x
        ];
}

console.log(/* tuple */[
      6,
      5
    ]);

console.log(/* tuple */[
      6,
      "adil"
    ]);

var names = /* tuple */[
  "Luke",
  "Han",
  "Leila",
  "Darth",
  "Yoda"
];

console.log(names);

exports.swap = swap;
exports.names = names;
/*  Not a pure module */
