// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


console.log(/* Circle */1);

function toString(field) {
  if (field) {
    if (field[0]) {
      return "O";
    } else {
      return "X";
    }
  } else {
    return "";
  }
}

var random = /* Marked */[/* Cross */0];

console.log(toString(random));

function isBigger(animal1, animal2) {
  if (animal1 || !animal2) {
    return false;
  } else {
    return true;
  }
}

console.log(isBigger(/* Bear */0, /* Deer */1));

function toString$1(param, param$1) {
  if (param$1) {
    if (param$1[0]) {
      return "O";
    } else {
      return "X";
    }
  } else {
    return "";
  }
}

console.log(toString$1(undefined, /* Marked */[/* Cross */0]));

var nextTurn = /* Circle */1;

exports.nextTurn = nextTurn;
exports.random = random;
exports.isBigger = isBigger;
exports.toString = toString$1;
/*  Not a pure module */
