// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");

var toLowercase = $$String.lowercase_ascii;

function getAnimal(anim) {
  return "this is " + anim;
}

function getAnimalAgain(anim) {
  return "this is " + anim;
}

function getTitle(cond, exp) {
  if (cond) {
    return exp;
  } else {
    return exp + " worskhop";
  }
}

var num = 51;

var cat = "ragdoll";

var dog = "husky";

exports.num = num;
exports.toLowercase = toLowercase;
exports.cat = cat;
exports.dog = dog;
exports.getAnimal = getAnimal;
exports.getAnimalAgain = getAnimalAgain;
exports.getTitle = getTitle;
/* No side effect */
