// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

var han = [
  "Han",
  "Solo",
  "Pilot"
];

var createArray = Caml_array.caml_make_vect;

var newOne = Caml_array.caml_make_vect(5, "Field");

console.log(newOne);

console.log(Caml_array.caml_array_get(han, 2));

if (han.length !== 3) {
  throw [
        Caml_builtin_exceptions.match_failure,
        /* tuple */[
          "Arrays.re",
          14,
          4
        ]
      ];
}

var firstname = han[0];

var lastname = han[1];

var occupation = han[2];

console.log(firstname);

function getFirstName(param) {
  if (param.length !== 3) {
    throw [
          Caml_builtin_exceptions.match_failure,
          /* tuple */[
            "Arrays.re",
            18,
            19
          ]
        ];
  }
  var firstname = param[0];
  var lastname = param[1];
  return [
          firstname,
          lastname
        ];
}

console.log(getFirstName(han));

exports.han = han;
exports.createArray = createArray;
exports.newOne = newOne;
exports.firstname = firstname;
exports.lastname = lastname;
exports.occupation = occupation;
exports.getFirstName = getFirstName;
/*  Not a pure module */
