// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

var list = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* :: */[
        4,
        /* [] */0
      ]
    ]
  ]
];

var list2 = /* :: */[
  "adil",
  /* :: */[
    "shaikh",
    /* :: */[
      "hello",
      /* :: */[
        "how r u",
        /* :: */[
          "wow",
          /* [] */0
        ]
      ]
    ]
  ]
];

function getLength(randomList) {
  console.log("ENTERED");
  console.log(randomList);
  if (randomList) {
    var tail = randomList[1];
    console.log(tail);
    return 1 + getLength(tail) | 0;
  }
  console.log("HERE 1");
  return 0;
}

console.log("Final length is " + String(getLength(list)));

var newList_001 = /* :: */[
  "black sheep",
  list2
];

var newList = /* :: */[
  "baba",
  newList_001
];

console.log(newList);

var listOne = /* :: */[
  "one",
  /* :: */[
    "two",
    /* [] */0
  ]
];

var listTwo = /* :: */[
  "three",
  /* :: */[
    "four",
    /* :: */[
      "five",
      /* [] */0
    ]
  ]
];

var mergedList = Pervasives.$at(listOne, listTwo);

console.log(mergedList);

exports.list = list;
exports.list2 = list2;
exports.getLength = getLength;
exports.newList = newList;
exports.listOne = listOne;
exports.listTwo = listTwo;
exports.mergedList = mergedList;
/*  Not a pure module */
