// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

var isEqual = Caml_obj.caml_equal(/* tuple */[
      7,
      2
    ], /* tuple */[
      7,
      2
    ]);

console.log(isEqual);

var isEqual$1 = /* tuple */[
  1,
  2
] === /* tuple */[
  1,
  2
];

console.log(isEqual$1);

var one = /* tuple */[
  7,
  2
];

var isEqual$2 = one === one;

console.log(isEqual$2);

var two = one;

exports.one = one;
exports.two = two;
exports.isEqual = isEqual$2;
/* isEqual Not a pure module */
