// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

console.log(11);

console.log(1);

console.log(51);

console.log(5e2);

console.log(true);

console.log(true);

console.log(true);

console.log(true);

console.log(false);

console.log(/* "r" */114);

console.log(4);

console.log(/* "d" */100);

console.log(Caml_format.caml_int_of_string("1234"));

console.log(String(123));

console.log("12" + (String(3) + "13"));

console.log($$String.make(1, /* "r" */114));

var test = 11;

var test2 = 1;

var test3 = 51;

var test4 = 5e2;

exports.test = test;
exports.test2 = test2;
exports.test3 = test3;
exports.test4 = test4;
/*  Not a pure module */
