// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


console.log(5);

console.log(10);

function getFirst(param) {
  return param[0];
}

console.log(24);

function getName(param) {
  return /* tuple */[
          "adil",
          "shaikh"
        ];
}

var firstname = "adil";

var secondname = "shaikh";

console.log("adil shaikh");

var luke = /* tuple */[
  "Lake",
  "Johnny",
  "Jedi"
];

var han = /* tuple */[
  "Han",
  "Solo",
  "Pilot"
];

var x = 5;

var z = 10;

var name = firstname;

var last = secondname;

exports.luke = luke;
exports.han = han;
exports.x = x;
exports.z = z;
exports.getFirst = getFirst;
exports.getName = getName;
exports.name = name;
exports.last = last;
/*  Not a pure module */
