// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function add(a) {
  return a + 5 | 0;
}

var multiply = Caml_int32.imul;

function composite(func1, func2, value) {
  return Curry._1(func1, Curry._1(func2, value));
}

function addMultiply(param) {
  return Caml_int32.imul(5, param) + 5 | 0;
}

console.log(addMultiply(5));

exports.add = add;
exports.multiply = multiply;
exports.composite = composite;
exports.addMultiply = addMultiply;
/*  Not a pure module */
