// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function add(a) {
  return a + 5 | 0;
}

function multiple(a) {
  return Caml_int32.imul(a, 5);
}

function subtract(a) {
  return 100 - a | 0;
}

function toString(a, prefix) {
  return prefix + (" " + String(a));
}

var temp = toString(45, "Hello");

console.log(temp);

function toString$1(prefix, a) {
  return prefix + (" " + String(a));
}

var temp$1 = toString$1("Welcome", 40);

console.log(temp$1);

exports.add = add;
exports.multiple = multiple;
exports.subtract = subtract;
exports.toString = toString$1;
exports.temp = temp$1;
/* temp Not a pure module */
