// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function getInt(a) {
  return a + 8 | 0;
}

function getIntInBlock(a) {
  return a + 8 | 0;
}

console.log(84);

console.log(14);

function getInts(a, b) {
  return a + b | 0;
}

console.log(10);

function curried(param) {
  return 8 + param | 0;
}

console.log(curried);

var result = 12;

console.log(result);

console.log("##########");

function func(y) {
  return 10 + y | 0;
}

console.log(func(2));

console.log(func(3));

function convert(prim) {
  return String(prim);
}

console.log(String(12));

var x = 20;

exports.getInt = getInt;
exports.getIntInBlock = getIntInBlock;
exports.getInts = getInts;
exports.curried = curried;
exports.result = result;
exports.func = func;
exports.x = x;
exports.convert = convert;
/*  Not a pure module */
