// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

console.log(5);

var divide = Caml_int32.div;

console.log(5);

function multiply(integer1Opt, integer2Opt, param) {
  var integer1 = integer1Opt !== undefined ? integer1Opt : 5;
  var integer2 = integer2Opt !== undefined ? integer2Opt : 7;
  return Caml_int32.imul(integer1, integer2);
}

console.log(multiply(2, 5, undefined));

console.log(multiply(2, undefined, undefined));

console.log(multiply(undefined, undefined, undefined));

var temp = 5;

exports.divide = divide;
exports.temp = temp;
exports.multiply = multiply;
/*  Not a pure module */
