// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function factorial(n) {
  if (n <= 1) {
    return 1;
  } else {
    return Caml_int32.imul(n, factorial(n - 1 | 0));
  }
}

console.log(factorial(10));

function isEven(num) {
  if (num === 0) {
    return true;
  } else {
    return isOdd(num - 1 | 0);
  }
}

function isOdd(num) {
  if (num === 0) {
    return false;
  } else {
    return isEven(num - 1 | 0);
  }
}

console.log(isOdd(123));

exports.factorial = factorial;
exports.isEven = isEven;
exports.isOdd = isOdd;
/*  Not a pure module */
